name: XMLTV Schedules Direct Grabber
version: "1.1.1"
slug: xmltv-grabber
description: Grabs TV listings from Schedules Direct using tv_grab_zz_sdjson
url: https://github.com/ricks03/ha-xmltv-grabber
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
startup: services
boot: auto
options:
  schedulesdirect_username: ""
  schedulesdirect_password: ""
  update_hour: 3
  days: 7
  lineups: []
schema:
  schedulesdirect_username: str
  schedulesdirect_password: password
  update_hour: int(0,23)
  days: int(1,14)
  lineups:
    - str?
map:
  - share:rw